global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: order-status
    metrics_path: /metrics
    static_configs:
      - targets: ["order-status-service:8090"]

  - job_name: outbox-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["outbox-worker:8085"]
