global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway
    static_configs:
      - targets: ["api-gateway:8080"]

  - job_name: outbox-worker
    static_configs:
      - targets: ["outbox-worker:8085"]

  - job_name: order-status-service
    static_configs:
      - targets: ["order-status-service:8090"]
